### ISSUE TITLE
HLD doesn't work for undirected graphs.

### ISSUE THREAD

**Issue by TimonKnigge** [TimonKnigge/TCR#4]
The HLD code claims '`vvi &graph; // graph can be graph or childs only`', but this is not the case. Take the following 7 vertex graph:

1 3

1 4

2 3

2 4

If we store this graph bidirectionally (a \in E[b] <=> b \in E[a]), the hld dfs will loop infinitely. I thought about changing the if-condition [here](https://github.com/TimonKnigge/TCR/blob/master/snippets/graphs/heavylight.cpp#L12) into `d[v]<0`, but then the LCA query 2,4 does not terminate.

**Comment by RagnarGrootKoerkamp** [comment]
The current code only works for trees, not for graphs with cycles or DAGs, since the lca is only uniquely defined for trees anyway.

**Comment by TimonKnigge** [comment]
No idea what I was thinking when I wrote this :upside_down_face:
